version: '3.7'

services:
    php-httpd:
        image: php:8.0-apache
        ports:
            - 90:80
        volumes:
            - "./DocumentRoot:/var/www/html"

    mariadb:
        image: mariadb:10.8
        volumes:
            - mariadb-volume:/var/lib/mysql
        environment:
            TZ: "America/Sao_Paulo"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "rootpwd"
            MYSQL_USER: 'kaell'
            MYSQL_PASSWORD: '123'
            MYSQL_DATABASE: 'testdb'

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - 'mariadb:db'
        ports:
            - 8081:80

volumes:
    mariadb-volume:
